# -*- coding: utf-8 -*-
"""meu primeiro algorotimo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEM6mWXqekv_cFoihNLhdTDe2WbI71Kn
"""



x = 7
print('O valor de x é ',x, 'e o dobro é', x*2)

nome = "willamy Gomes"
print(nome)

print('Eu,', nome, 'tirei um', x, 'na prova de Pyton')

"""Concatenação"""

print('Testando as variavel', x,'(numero),', nome,'(texto)')

"""Input
* Armazenar a informação digitada pelo usuario em uma variavel
* o Dado armazenado sempre será um texto
"""

nome = input ('Digite o nome do Usuario ')
print(nome)

valor = input ('Digite uma nota ')
print(nome, 'Sua nota é,',valor)

